coverage_service: html
xcodeproj: /Users/administrator/Downloads/pritam/pritamIosCI/pritamIosCI.xcodeproj
scheme: pritamIosCI
configuration: Debug
output_directory: slather-report
html_enabled: true
binary_basename: pritamIosCI
