xcodebuild test \
  -project pritamIosCI/pritamIosCI.xcodeproj \
  -scheme pritamIosCI \
  -destination 'platform=iOS Simulator,name=iPhone 15' \
  -enableCodeCoverage YES \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGNING_ALLOWED=NO
