# .slather.yml
coverage_service: html
xcodeproj: /Users/administrator/Downloads/pritam/pritamIosCI/pritamIosCI.xcodeproj
scheme: pritamIosCI
configuration: Debug
output_directory: slather-report
html:
  output: true
  pretty: true

