name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app
        # or match your version like 15.0, 14.3 etc.

      - name: Install Dependencies (e.g., CocoaPods)
        run: |
          if [ -f "Podfile" ]; then
            gem install cocoapods
            pod install
          fi

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: |
          swiftlint

      - name: Build and Run Tests
        run: |
          xcodebuild test \
            -scheme YourAppScheme \
            -workspace YourApp.xcworkspace \  # use -project if not using workspace
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' \
            ONLY_ACTIVE_ARCH=NO

      # Optional: Archive the app
      - name: Archive App
        run: |
          xcodebuild archive \
            -scheme YourAppScheme \
            -workspace YourApp.xcworkspace \
            -archivePath $PWD/build/YourApp.xcarchive \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES
